### ISSUE TITLE
readlink doesn't exist in msys environment or busybox neither

### ISSUE THREAD

**Issue by deajan** [mkropat/sh-realpath#2]
Hello,

I've integrated your code into my project at https://github.com/deajan/osync
My project aims to run on Linux / *BSD / MacOS and MSYS.
Other people also tried to integrate my project into Busybox.

It relies on your sh_realpath integration which is great, but still relies on readlink.
Would you mind integrate the poor_man_readlink as fallback alternative as stated in your README ?

Regards,
Ozy.

**Comment by mkropat** [comment]
Sure, I can make an attempt at implementing a readlink fallback sometime this week. I can see how it'd be useful to run this code on both Msys and Busybox.

**Comment by mkropat** [comment]
I've added new code that can emulate readink on systems where it's missing. I've done some preliminary testing on Linux, OS X, and Busybox. I couldn't get the tests to run under Msys, so I don't know if it will work there.

Please give it a try and let me know if it works.

**Comment by deajan** [comment]
Thank you, i'll create a new dev branch soon with your fixes and see what happens on BSD and MSYS.
As for Busybox, i'll have to ask a guy on github who uses my project with that platform.

**Comment by deajan** [comment]
Hello,

Sorry for being (really) late with this.

I cannot get your implementation to work.
The realpath emulation doesn't work for me on CentOS.
Even the system command realpath doesn't work as soon as i use debugging.
The busybox developper also told be it didn't work out for him.

Could you investigate the issue and what would you need in order to do so ?

**Comment by mkropat** [comment]
No worries, sure, I can take another look at it maybe sometime this week or next.

I know I haven't tested it on CentOS, so that's a good place to start. I thought I tested it on Busybox, but maybe that support still needs more work.

**Comment by deajan** [comment]
Anything new yet ?

**Comment by GitMensch** [comment]
Seems like there is no update so this issue may be closed.
As it actually was one of the top items in searching for mingw + readlink:

`mingw-get.exe install msys-coreutils-ext` solves this.

**Comment by mkropat** [comment]
Thank you for the pointer. Closing the issue in case it helps dropping this on search engine rankings.
